package umap

// testutil_test.go provides helpers for loading JSON test data files
// generated by testdata/generate.py.

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// testdataDir returns the path to the testdata directory.
func testdataDir() string {
	return filepath.Join("testdata")
}

// loadJSON reads a JSON file from testdata/ and unmarshals it into v.
// Handles Python-generated JSON that may contain Infinity, -Infinity, and NaN
// (produced by json.dump with allow_nan=True).
func loadJSON(t *testing.T, relPath string, v any) {
	t.Helper()
	path := filepath.Join(testdataDir(), relPath)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read test data %s: %v", relPath, err)
	}
	// Replace Python JSON non-standard tokens with valid JSON values.
	// Infinity → 1e+308 (close to math.MaxFloat64), NaN → null.
	// We must be careful not to replace substrings within strings.
	s := string(data)
	s = strings.ReplaceAll(s, "-Infinity", "-1.7976931348623157e+308")
	s = strings.ReplaceAll(s, "Infinity", "1.7976931348623157e+308")
	s = strings.ReplaceAll(s, "NaN", "null")
	if err := json.Unmarshal([]byte(s), v); err != nil {
		t.Fatalf("failed to unmarshal test data %s: %v", relPath, err)
	}
}

// approxEqual checks if two float64 values are approximately equal.
func approxEqual(a, b, tol float64) bool {
	if math.IsNaN(a) && math.IsNaN(b) {
		return true
	}
	if math.IsInf(a, 1) && math.IsInf(b, 1) {
		return true
	}
	if math.IsInf(a, -1) && math.IsInf(b, -1) {
		return true
	}
	return math.Abs(a-b) <= tol
}

// assertSliceApprox checks that two float64 slices match within tolerance.
func assertSliceApprox(t *testing.T, name string, got, want []float64, tol float64) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("%s: length mismatch: got %d, want %d", name, len(got), len(want))
	}
	for i := range got {
		if !approxEqual(got[i], want[i], tol) {
			t.Errorf("%s[%d]: got %v, want %v (tol=%v)", name, i, got[i], want[i], tol)
		}
	}
}

// maxAbsDiff returns the maximum absolute difference between two matrices.
func maxAbsDiff(a, b [][]float64) float64 {
	maxD := 0.0
	for i := range a {
		for j := range a[i] {
			d := math.Abs(a[i][j] - b[i][j])
			if d > maxD {
				maxD = d
			}
		}
	}
	return maxD
}

// rmseDiff returns the RMSE between two matrices.
func rmseDiff(a, b [][]float64) float64 {
	var sum float64
	var count int
	for i := range a {
		for j := range a[i] {
			d := a[i][j] - b[i][j]
			sum += d * d
			count++
		}
	}
	if count == 0 {
		return 0
	}
	return math.Sqrt(sum / float64(count))
}

// float64sToInts converts []float64 to []int (truncating).
func float64sToInts(f []float64) []int {
	result := make([]int, len(f))
	for i, v := range f {
		result[i] = int(v)
	}
	return result
}
